export const siteConfig = {
  person: "Hasnane Nawaz",
  name: "Hasnane Nawaz - Social Media Marketing Portfolio",
  role: "Social Media Marketer | Content & Growth Strategy",
  url: "https://www.hasnanenawaz.in",
  email: "hasnanenawaz@gmail.com",
  phone: "+91 8269786782",
  location: "Durg, Chhattisgarh, India",
  description:
    "Portfolio of Hasnane Nawaz, a social media marketer and growth strategist building engaged communities, lead engines, and revenue-focused campaigns.",
  keywords: [
    "Hasnane Nawaz",
    "social media marketer",
    "growth strategist",
    "content strategy",
    "community growth",
    "lead generation",
    "Meta Ads",
    "Durg Chhattisgarh",
    "marketing portfolio",
  ],
  personSchema: {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "Hasnane Nawaz",
    url: "https://www.hasnanenawaz.in",
    image: "https://www.hasnanenawaz.in/hasnane.png",
    jobTitle: "Social Media Marketer and Growth Strategist",
    description:
      "Social media marketer building engaged communities, generating qualified leads, and executing revenue-focused campaigns.",
    email: "mailto:hasnanenawaz@gmail.com",
    telephone: "+91 8269786782",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Durg",
      addressRegion: "Chhattisgarh",
      addressCountry: "IN",
    },
    knowsAbout: [
      "Social Media Marketing",
      "Lead Generation",
      "Content Strategy",
      "Community Growth",
      "Meta Ads",
      "Sales Operations",
      "Campaign Planning",
      "Copywriting",
      "CPC Optimization",
    ],
  },
  websiteSchema: {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Hasnane Nawaz Portfolio",
    url: "https://www.hasnanenawaz.in",
    description:
      "Portfolio of Hasnane Nawaz, social media marketer and growth strategist.",
    author: {
      "@type": "Person",
      name: "Hasnane Nawaz",
      url: "https://www.hasnanenawaz.in",
    },
  },
};
